// Generated by gencpp from file hit_spider/hexapod_RPY.msg
// DO NOT EDIT!


#ifndef HIT_SPIDER_MESSAGE_HEXAPOD_RPY_H
#define HIT_SPIDER_MESSAGE_HEXAPOD_RPY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hit_spider
{
template <class ContainerAllocator>
struct hexapod_RPY_
{
  typedef hexapod_RPY_<ContainerAllocator> Type;

  hexapod_RPY_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  hexapod_RPY_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::hit_spider::hexapod_RPY_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hit_spider::hexapod_RPY_<ContainerAllocator> const> ConstPtr;

}; // struct hexapod_RPY_

typedef ::hit_spider::hexapod_RPY_<std::allocator<void> > hexapod_RPY;

typedef boost::shared_ptr< ::hit_spider::hexapod_RPY > hexapod_RPYPtr;
typedef boost::shared_ptr< ::hit_spider::hexapod_RPY const> hexapod_RPYConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hit_spider::hexapod_RPY_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hit_spider::hexapod_RPY_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hit_spider::hexapod_RPY_<ContainerAllocator1> & lhs, const ::hit_spider::hexapod_RPY_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hit_spider::hexapod_RPY_<ContainerAllocator1> & lhs, const ::hit_spider::hexapod_RPY_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hit_spider

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hit_spider::hexapod_RPY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hit_spider::hexapod_RPY_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hit_spider::hexapod_RPY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hit_spider::hexapod_RPY_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hit_spider::hexapod_RPY_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hit_spider::hexapod_RPY_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hit_spider::hexapod_RPY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eeec8b25a660789a89540dedcb2b06d6";
  }

  static const char* value(const ::hit_spider::hexapod_RPY_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeeec8b25a660789aULL;
  static const uint64_t static_value2 = 0x89540dedcb2b06d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::hit_spider::hexapod_RPY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hit_spider/hexapod_RPY";
  }

  static const char* value(const ::hit_spider::hexapod_RPY_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hit_spider::hexapod_RPY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::hit_spider::hexapod_RPY_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hit_spider::hexapod_RPY_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hexapod_RPY_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hit_spider::hexapod_RPY_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hit_spider::hexapod_RPY_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIT_SPIDER_MESSAGE_HEXAPOD_RPY_H
